# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Asurin
tagline:             'Software Developer'
description:         'Asurin <br /> Software Developer <br />'
url:                 https://asurinsaka.github.io/
baseurl:             ''
github_username:     asurinsaka

plugins:                [jekyll-paginate, jekyll-last-modified-at]
paginate:            5

# About/contact
author:
  name:              Asurin
  email:             qiaozha@gmail.com

# Custom vars
version:             1.0.0


