# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Asurin
tagline:             'System Engineer, Data Scientist, Web Developer'
description:         'Asurin <br /> System Engineer <br /> Web Developer <br />'
url:                 http://localhost:4000/
baseurl:             ''

gems:                [jekyll-paginate, jekyll-last-modified-at]
paginate:            5

# About/contact
author:
  name:              Mark Otto
#  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
